services:
  - type: web
    name: meeting-scheduler
    env: node
    buildCommand: npm install && cd client && npm install && npm run build && cd ..
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: TIMEZONE
        value: America/New_York
